name: weather_kit
description: A dart library for interfacing with the Apple WeatherKit API.
version: 0.2.0
homepage: https://github.com/mafreud/weather_kit
repository: https://github.com/mafreud/weather_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_jsonwebtoken: ^2.8.2
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
